### ISSUE TITLE
Questions about the accuracy of the paper

### ISSUE THREAD

**Issue by FireTracer** [venkateshsathya/RML22#2]
In the paper, it is introduced that RML22 includes 10 modulation types, while in open source code, there are 11 types, and the RML dataset downloaded directly is also 11 types. So we want to know if the accuracy of 0.61 reported in the paper corresponds to 10 types or 11 types? thank.

![image](https://github.com/user-attachments/assets/ef95bf68-cbee-42d3-bdce-ef35b94db148)

![image](https://github.com/user-attachments/assets/943acfab-c0cd-4cbe-9103-ea8b7ba1f8d4)

**Comment by venkateshsathya** [comment]
These are the ten modulation types that should be present in the dataset and those used in this work: transmitters = {
    "discrete":[transmitter_bpsk, transmitter_qpsk, transmitter_8psk, transmitter_pam4, transmitter_qam16, transmitter_qam64, transmitter_gfsk, transmitter_cpfsk],
    "continuous":[transmitter_fm, transmitter_am]
    }

**Comment by FireTracer** [comment]
Thanks for your prompt reply.

**Comment by FireTracer** [comment]
In addition, for datasets of 10 categories. Using the network you built to train the downloaded dataset, the accuracy is approximately 61-62%, which is consistent with the situation in this article. However, based on the RML22 dataset simulated locally with open-source code, the accuracy is 68-70%. Have you noticed this situation? What could be the possible reason for this?
In essence, when reproducing the RML2016 dataset previously, I found that the accuracy of the reproduced dataset was much higher than the RML2016.10A dataset publicly downloaded by Oshea.

If you could provide more knowledge to help me solve this confusion, I would be very grateful.


![image](https://github.com/user-attachments/assets/c108b720-5bac-44b8-a217-d17fe5c92f20)

![image](https://github.com/user-attachments/assets/40731fa8-df68-4d36-b680-2da29c28b156)

**Comment by venkateshsathya** [comment]
Hi Fire tracer. I am not sure what could be the reason, but I believe that these are superficial things and not pertinent to the research ideas I am discussing, I am therefore closing this thread.

**Comment by venkateshsathya** [comment]
If you are particular looking at a specific research problem, send me your ideas to discuss at swanky1986@gmail.com and I will share my thoughts.
